### ISSUE TITLE
مشکل در MaltParse

### ISSUE THREAD

**Issue by azarezade** [roshan-research/hazm#112]
سلام
برای به دست آوردن درخت وابستگی پس از اجرای نمونه کد شما به خطای زیر بر میخورم
```
raise Exception("MaltParser parsing failed: %s" % (' '.join(cmd)))
Exception: MaltParser parsing failed: java -jar resources/malt.jar -w resources -c langModel.mco -i /Users/Ali/...
```
از آخرین نسخه استفاده می‌کنم و سیستم عامل مک دارم
ممنون

**Comment by nournia** [comment]
<div dir=rtl>

سلام
از اینکه جاوا در سیستم نصب هست مطمئن هستید؟
به نظرم خطا رو برای مک جستجو کنید، چون فکر نمی‌کنم مشکل از هضم باشه.

**Comment by azarezade** [comment]
بله جاوا نصب است.
آیا نیاز به ورژن خاصی دارد یا آخرین ورژن کافی است.

**Comment by nournia** [comment]
<div dir=rtl>

من سعی می‌کنم با یک ماشین مک امتحان کنم ولی اونقدر که می‌دونم مشکلی وجود نداشته. به نظرم شما هم روی یک سیستم مک دیگه تست کنید.

**Comment by azarezade** [comment]
<p dir='rtl'>
ممنون
باشه حتما
</p>

**Comment by mahsaSH717** [comment]
سلام من هم متاسفانه همین مشکل رو روی ابونتو دارم و اصلا هیچ جا اشاره نشده این مشکل به خاطر چیه
