### ISSUE TITLE
نرمال کردن نوشته‌های نوشته‌شده با ساختار نوشته‌های شبکه‌ها اجتماعی

### ISSUE THREAD

**Issue by sara8086** [roshan-research/hazm#117]
در بسیاری از نوشته‌ها در شبکه‌های اجتماعی از کاراکترهای ویژه‌ای برای انتقال مفهوم فارسی استفاده میشود که تاحد بالایی قابل حدس هستند.
مانند نمونه های زیر از اینستاگرام : 

```
گـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍرمای عشقـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍش 
مثـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍل حـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍرارت 
خـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍورشیـב بـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍوב 
همـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍـہ ازش استـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍفاـבـہ 
میکـٍـٍـٍـٍـٍْـٍْـٍْـٍْـٍْـٍـٍـٍـٍـٍرבל
```

یا

```
☜تنـــــد میــــــره ۅقتـے همـہ چـے عـالیـہ 
☜آرۅمـــــ میـــرہ ۅقتـے جـا همـہ خـالیـــــہ 
```

بابت متن ناثواب نوشته‌ها پیشاپیش عذرخواهی میکنم، جنس این نوشته ها معمولا از این نوعند.

آیا راهی برای پردازش این متن‌ها و دیتاستی از اینها موجود است؟ آیا هضم برنامه‌ای برای نرمال کردن این متون دارد؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
خوبه که بتونیم این نوشته ها رو هم نرمال کنیم. البته نمی دونم چقدر به استفاده های پردازشی کمک می کنن.
در هر حال ممنون می شم که اگر فرصت دارید فهرستی از کاراکترهایی که باید تبدیل بشن و همچنین معادلشون درست کنید.

**Comment by sara8086** [comment]
طبیعتا این مدل نوشته ها تا مناسب شدن برای استفاده به عنوان ساختار زبانی قابل پردازش و ارزشمند فاصله‌ی زیادی دارند اما پردازش‌های ساده و در حد جمله واره‌ها و کلمات غالب در شبکه‌های اجتماعی برای تحلیلگران این فضا با توجه به حجم بسیار زیاد محتوای تولید شده با این ساختار کاربردهای ساده‌ای دارند.

من لیستها و پترن‌های ساده‌ای تاکنون در این فضا یافته و همچنان درحال جمع‌آوری هستم و اگر به جای خوبی برسد حتما تقدیم پروژه هضم میکنم.

پیشنهادات و منابع این فضا را اگر دوستان اطلاع دارند برای بنده درصورت امکان ارسال کنند. 
ممنون

**Comment by sir-kokabi** [comment]
<div dir="rtl">
این مشکل تا حد بسیار خوبی حل شده است و همچنان در حال توسعه است. 

در نسخه‌های بعدی هضم، این متن‌ها نیز نرمالسازی می‌شود.
</div>
