### ISSUE TITLE
documentation for hazm

### ISSUE THREAD

**Issue by alisharifi2000** [roshan-research/hazm#129]
hi . where i can find documentation for this package . i google it but i couldnt find any documentation for hazm .
thank you.

**Comment by aidinism** [comment]
http://www.sobhe.ir/hazm/

**Comment by nournia** [comment]
<div dir="rtl">
سلام
داریم روش کار می‌کنیم ولی خب فعلا این هست:

http://www.sobhe.ir/hazm/docs/

**Comment by alisharifi2000** [comment]
خواستم تشکر کنم از زحمات فراوان برای ارتقا و بهبود هضم .

**Comment by nournia** [comment]
<div dir=rtl>

ممنون. موفق باشید.

**Comment by sir-kokabi** [comment]
مستندات هضم:
https://www.roshan-ai.ir/hazm/docs/
