### ISSUE TITLE
خطا در خروجی هضم 

### ISSUE THREAD

**Issue by mansourehm** [roshan-research/hazm#144]
سلام وقتتون بخیر.
با توجه به مواردی که توی سایت بود هضم رو نصب کردم اما این دستورات خطا میده 

tagger = POSTagger(model='resources/postagger.model')
tagger.tag(word_tokenize('ما بسیار کتاب می‌خوانیم'))

و این خطا رو نشون میده

  from wapiti import Model
ModuleNotFoundError: No module named 'wapiti'

**Comment by tuytoosh** [comment]
I have the same error in windows 10 and python v3.4.3

**Comment by mansourehm** [comment]
> سلام
> لطفا بخش نصب روی ویندوز هضم رو نگاه کنید، اونجا گفته چطور نصب کنید.
سلام
مرسی تشکر. 
ببخشید اگر WSL رو میگید. من برای لینکوس در موردش دیدم. (شاید هم من اشتباه می کنم ) 
میشه لطفا بیشتر توضیح بدید ؟

**Comment by tuytoosh** [comment]
@mansourehm my problem solved by running it in `WSL` in windows 10, you need to enable that feature and install `python` and `pip` on that and after that install `hazm` in `WSL`

**Comment by floweri** [comment]
منم این مشکل رو دارم و
WSl رو در ویندوز فعال کردم
باید یک توزیع لینوکس هم نصب بشه؟

**Comment by fateme1373** [comment]
> سلام وقتتون بخیر.
> با توجه به مواردی که توی سایت بود هضم رو نصب کردم اما این دستورات خطا میده
> 
> tagger = POSTagger(model='resources/postagger.model')
> tagger.tag(word_tokenize('ما بسیار کتاب می‌خوانیم'))
> 
> و این خطا رو نشون میده
> 
> from wapiti import Model
> ModuleNotFoundError: No module named 'wapiti'

سلام من هم این مشکل رو دارم، توی سایت هضم گفته فایلی به اسم
resources
رو دانلود و تو مسیر پروژه نصب کنیم
C:\Users\Karmian\Anaconda3
مثلا اینجا. ولی نمیتونه اون فایل 
postagger.model
و مدل wapiti
رو پیدا کنه، میشه یکی از دوستان راهنمایی کنه؟
اون چیزی که به اسم wsl 
معرفی شده هم برای لینوکس هست
ولی ما ویندوز 10 هستیم

**Comment by tuytoosh** [comment]
@fateme1373 @floweri 

Hi, [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) is a Windows Subsystem for Linux that simply you can enable it on windows. no extra work required.

**Comment by zeintiz** [comment]
what about windows 7 ? WLS ,Windows Linux Subsystem does not exist and cannot be enabled/installed on Windows 7. what can i do??

**Comment by tuytoosh** [comment]
@zeintiz An alternative to WSL could be working on a virtualization software like "virtual box" with a Linux distribution mounted on that.

**Comment by zeintiz** [comment]
> @zeintiz An alternative to WSL could be working on a virtualization software like "virtual box" with a Linux distribution mounted on that.

tankx.

**Comment by samiravaez** [comment]
Can someone give more tips on this error or explain it more? I followed the instructions and installed hazm on WSL2 Ubuntu 16.04 LTS. but i'm still getting this error:
ModuleNotFoundError: No module named 'wapiti'

**Comment by ebad84** [comment]
you can use the api!!!
sniff this url : https://www.sobhe.ir/hazm/demo/
it will be work for everyone who can't use wapiti in windows
but it need connection

انگلیسی گفتم :/ هورا :|

**Comment by kokabi1365** [comment]
Duplicate of #98

**Comment by sir-kokabi** [comment]
در حال حاضر برای استفاده از هضم روی ویندوز باید از WSL استفاده کنید.
طبق راهنمای ویدیویی عمل کنید:
https://www.roshan-ai.ir/hazm/docs/
