### ISSUE TITLE
اصلاح کاراکتر اشتباه نیم‌فاصلهٔ 

### ISSUE THREAD

**Issue by samehraban** [roshan-research/hazm#15]
<div dir="rtl">اوّلین باری که می‌خواستم از نیم‌فاصله استفاده کنم توی مایکروسافت ورد بود و دکمه‌های ترکیبی که استفاده می‌کردم کاراکتر ¬ رو توی متن می‌گذاشت و توی ورد مثل نیم‌فاصله بود. اگر این کاراکتر رو هم تصحیح کنید خوب می‌شه.</div>

**Comment by sir-kokabi** [comment]
اسم این کاراکتر logical negation symbol هست که در بعضی از متن‌ها مثلاً متن‌های مربوط به جبر بولی معنای خاصی داره.
`If A = true, ¬A = false`
بنابراین نمی‌تونیم حذفش کنیم.
