### ISSUE TITLE
Dependency Parser not working!

### ISSUE THREAD

**Issue by csarami** [roshan-research/hazm#172]
درود بر شما
من وقتی کد زیر رو اجرا می کنم
parser = DependencyParser(tagger=tagger, lemmatizer=lemmatizer)
parser.parse(word_tokenize('زنگ‌ها برای که به صدا درمی‌آید؟'))

خطاهای زیر نمایش می دن؟
Exception: MaltParser parsing failed: java -jar resources/malt.jar -w resources -c langModel.mco -i /content/resources/malt_input.conllirwsfu38 -o /content/resources/malt_output.conllpn40me7y -m parse

جاوا هم اینستال هست:
javac 1.8.0_222

ممنون میشم اگه کمک کنین

**Comment by sakina-mosavi** [comment]
سلام خدمت شما
من در پایتون کار میکنم و وقتی این کود رو اجرا میکنم خطا میده

parser = DependencyParser(tagger=tagger, lemmatizer=lemmatizer)
parser.parse(word_tokenize('زنگ‌ها برای که به صدا درمی‌آید؟'))

**Comment by nournia** [comment]
<div dir=rtl>

سلام
از ویندوز استفاده می‌کنید؟
مطمئن هستید که متغیرهای سیستمی مثل JAVA_HOME درست تنظیم شدن؟

**Comment by csarami** [comment]
نه با مک ( Mojave) کار می کنم.... ممنونم ... متغیرهای سیستمی رو چک می‌کنم.
