### ISSUE TITLE
خطا در استفاده از IOBTagger

### ISSUE THREAD

**Issue by ehsankhorasani** [roshan-research/hazm#173]
سلام
من مدل iob رو آموزش دادم و میخوام ازش استفاده کنم.
وقتی کد زیر رو اجرا میکنم خطا برمیگردونه:

```
from hazm import IOBTagger, word_tokenize
tagger = IOBTagger(model='resources/iob.model')
example = 'من به مدرسه میروم.'
tagger.tag(word_tokenize(example))
```

`>>> error: missing tokens, cannot apply pattern`

**Comment by nournia** [comment]
<div dir=rtl>

سلام
لطفا نگاهی به تست‌های داخل [فایل تعریف این کلاس](https://github.com/sobhe/hazm/blob/master/hazm/SequenceTagger.py) بندازید.
در این تست‌ها اول یک مدل ساده آموزش داده می‌شه و بعد مورد استفاده قرار می‌گیره.
