### ISSUE TITLE
hazm: POSTagger: ArgumentError: argument 2: <class 'TypeError'>: wrong type

### ISSUE THREAD

**Issue by aminkhod** [roshan-research/hazm#179]
با سلام
من در اجرای دستور زیر خطا دریافت میکنم.
`tagger = POSTagger(model='resources/postagger.model')`
`tagger = POSTagger()`
خطا:
`---------------------------------------------------------------------------`
`ArgumentError                             Traceback (most recent call last)`
`<ipython-input-16-1d74d781e0c1> in <module>`
`      1 tagger = POSTagger(model='resources/postagger.model')`
`----> 2 tagger = POSTagger()`
`      3 tagger.tag(word_tokenize('ما بسیار کتاب موانیم'))`

`~/.local/lib/python3.6/site-packages/hazm/SequenceTagger.py in __init__(self, patterns, **options)`
`     21         def __init__(self, patterns=[], **options):`
`     22                 from wapiti import Model`
`---> 23                 self.model = Model(patterns='\n'.join(patterns), **options)`
`     24 `
  `   25         def train(self, sentences):`

`~/.local/lib/python3.6/site-packages/wapiti/api.py in __init__(self, patterns, encoding, **options)`
`    283             self._model = _wapiti.api_new_model(`
`    284                 ctypes.pointer(self.options),`
`--> 285                 self.patterns`
`    286             )`
`    287 `

`ArgumentError: argument 2: <class 'TypeError'>: wrong type`

من از افزونه‌ ubuntu18.04  روی ویندوز ۱۰ استفاده میکنم و همینطور فایل‌های مربوط به مدل در پوشه‌ی پروژه و در resources قرار داده شده است.
پایتون 3.6.9
hazm آپگرید شده

و مورد جالبتر اینکه chunker کار می‌کنه. اما POSTagger خطا میده.

**Comment by nournia** [comment]
<div dir=rtl>

سلام
خطایی که باهاش مواجه می‌شید یه مقدار عجیب هست.
لطفا دقیقا مطابق [فرایند تست](https://github.com/sobhe/hazm/blob/master/.travis.yml) اجرا کنید ببینید مشکل حل می‌شه یا تغییر نمی‌کنه.
چون تست‌ها روی نسخه‌های مختلف پایتون اجرا می‌شن و نتیجه‌شون هم هیچ خطایی نداره. نمونه‌های داخل README هم تست می‌شن و درست کار می‌کنن.
