### ISSUE TITLE
لینک‌های پیکره‌ها خراب شده‌اند

### ISSUE THREAD

**Issue by amirmojiry** [roshan-research/hazm#180]
<div dir='rtl'>
سلام
لینک‌های پیکره‌ها و مجموعه داده‌هایی که در هضم استفاده شده‌اند از کار افتاده‌اند:

1. [بیجن‌خان](https://github.com/sobhe/hazm/blob/master/hazm/BijankhanReader.py): اکنون به [این جا](http://ece.ut.ac.ir/dbrg/bijankhan/Corpus/BijanKhan_Corpus_Processed.zip) لینک شده است که کار نمی‌کند. اما از [نسخه بایگانی‌شده‌ی صفحه‌ی پیکره‌ی بیجن‌خان](http://web.archive.org/web/20160506231607/http://ece.ut.ac.ir/DBRG/bijankhan/) قابل دانلود است.
2. [دادگان](https://github.com/sobhe/hazm/blob/master/hazm/DadeganReader.py): اکنون به [این جا](http://dadegan.ir/perdt/download) لینک شده است که به [این جا](https://www.peykaregan.ir/dataset/%D9%BE%DB%8C%DA%A9%D8%B1%D9%87-%D9%88%D8%A7%D8%A8%D8%B3%D8%AA%DA%AF%DB%8C-%D9%86%D8%AD%D9%88%DB%8C-%D8%B2%D8%A8%D8%A7%D9%86-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C) ارجاع داده می‌شود که برای دسترسی به آن باید در سایت پیکره‌گان عضو شد.
3. [دگربیان](https://github.com/sobhe/hazm/blob/master/hazm/DegarbayanReader.py): اکنون به [این جا](https://www.peykaregan.ir/dataset/%D9%BE%DB%8C%DA%A9%D8%B1%D9%87-%D8%AF%DA%AF%D8%B1%D8%A8%DB%8C%D8%A7%D9%86) لینک شده است که به [این جا](http://nlp.guilan.ac.ir/dataset/5) ارجاع می‌دهد که کار نمی‌کند. [نسخه بایگانی‌شده](http://web.archive.org/web/20190601232539/http://nlp.guilan.ac.ir/dataset/5). اکنون برای دسترسی به این مجموعه داده باید از [این فرم](https://nlp.guilan.ac.ir/datasets) استفاده کرد.
4. [همشهری](https://github.com/sobhe/hazm/blob/master/hazm/HamshahriReader.py): اکنون به [این جا](http://dbrg.ut.ac.ir/Hamshahri/download.html#version2) لینک شده است که @ahangarha در #89 گفته بود اما این لینک اکنون کار نمی‌کند. [نسخه بایگانی‌شده‌ی صفحه‌ی پیکره‌ی همشهری](http://web.archive.org/web/20190810001705/http://dbrg.ut.ac.ir/Hamshahri/download.html).
</div>

**Comment by nournia** [comment]
<div dir=rtl>

سلام
بسیار ممنونم از بررسی کاملی که داشتید. به نظر شما با این لینک‌ها چه کنیم؟

1. لینک‌ها رو اگر از سایت آرکایو بذاریم به نظر من خیلی صورت جالبی نداره ولی خب مخاطب دیگه لازم نیست دنبال داده‌ها بگرده.
2. لینک‌ها رو اگر خیلی کلی و به سایت مرجع بدیم، مخاطب وارد سایت می‌شه و خودش با گشتن در صفحه‌ها به نتیجه می‌رسه ولی خب باز هم زیاد راحت نیست.
3. می‌تونیم فقط به مقاله‌ها ارجاع بدیم و مخاطب بره خودش پیدا بکنه داده رو.

**Comment by mahdift** [comment]
متاسفانه لینک‌های داخل سایت آرکایو برای پیکره همشهری به صفحاتی از دراپباکس اشاره می‌کنه که اون ها هم خراب شده ن. به نظرم بهترین کار والبته خداپسندانه ترین(: کار اینه که اطلاعات پیکره‌های بالا اگر در اختیار دوستان هست جایی آپلود بشه و توسط پروژه به اونجا ارجاع داده بشه. هرچند این کار هزینه آپلود زیادی داره(در حد چند گیگ) اما به نظر مطمئن ترین راهه.

**Comment by nournia** [comment]
<div dir=rtl>

مشکل اینه که این پیکره‌ها مالکیت معنوی دارن و ما نمی‌تونیم اونها رو منتشر بکنیم.

**Comment by ahangarha** [comment]
البته فکر کنم منظورتون پروانه‌هایی باشه که اجازه بازنشر نمی‌دن. مگر نه، مالکیت معنوی، مانع بازنشر نیست.

**Comment by nournia** [comment]
<div dir=rtl>

بله درست می‌فرمایید.
یک مشکل دیگه در حوزه مالکیت معنوی پیکره‌ها اینه که برای بعضی از این داده‌ها حتی حقوق مالکیت معنوی درست مشخص نشده. یعنی اصلا معلوم نیست که می‌شه باهاشون چه کرد.

**Comment by ahangarha** [comment]
این، پیگیری می‌خواد. متاسفانه دوستان، اهمیت این موضوع رو درک نکرده‌اند که چرا داشتن پیکره آزاد، اهمیت داره.

نیاز هستی که بیشتر و بیشتر در این باره حرف بزنیم و از مسئولین بخواهیم که این پیکره‌ها رو آزاد منتشر کنند

**Comment by amirmojiry** [comment]
<div dir='rtl'>
در رابطه با آپلود اطلاعات پیکره ها در یک فضای دائمی (که @mahdift گفت) مشکلی وجود نداره و می تونم چنین فضایی رو در اختیار بگذارم اما همون طور که @nournia و @ahangarha  گفتند، مشکل مجوز نشر وجود داره. من موضوع رو با مسئولان هر 4 پیکره مطرح می کنم و اگر موافقت کنند، در جای مناسبی آپلود می کنم.
</div>

**Comment by nournia** [comment]
<div dir=rtl>

بسیار عالی.

**Comment by ahangarha** [comment]
@amirmojiry احیانا موفق شدید با مسئولین پیکره‌ها صحبت کنید؟
نتیجه رو (حتی اگر ناموفق بوده) لطفا مکتوب کنید.

**Comment by sir-kokabi** [comment]
متأسفانه برای بسیاری از این پیکره‌ها کسی همکار نمی‌کنه و حتی جواب نمی‌دن.

**Comment by ahangarha** [comment]
سال‌هاست از دوستان دعوت می‌کنم بیایم بنشینیم ببینیم چه کار می‌تونیم بکینم برای تهیه یک پیکره آزاد. کسی پاسخ مثبتی نمی‌ده.

با این حساب، وضعیت تغییری نخواهد کرد.

**Comment by mehrangta** [comment]
https://dbrg.ut.ac.ir/hamshahri/
https://drive.google.com/file/d/1D3yt99D0GcCRCbdKbUQGxbqjkeh91hTg/view
