### ISSUE TITLE
Add a native downloader for hazm

### ISSUE THREAD

**Issue by AlirezaTheH** [roshan-research/hazm#195]
I think it would be great to have a native command line downloader for downloading tagger models. Just like [NLTK](http://nltk.org/) and [spaCy](https://spacy.io):
```
python -m nltk.downloader all
python -m spacy download en
```

I can add a [click](https://github.com/pallets/click) based cli downloader and submit a PR for it.

**Comment by sir-kokabi** [comment]
به دلایلی که در این پول‌ریکوئست توضیح داده شده این ایشو بسته می‌شه.
https://github.com/roshan-research/hazm/pull/201#issuecomment-1636996373
