### ISSUE TITLE
(فحش)فیلتر کردن کلمات نامناسب

### ISSUE THREAD

**Issue by mmdbalkhi** [roshan-research/hazm#198]
<div dir="rtl">
سلام خسته نباشید کتابخانه جالبی هستش ولی فکر کنم این قابلیت رو نداره  (اگر که داشته باشه بسیار عالی) من قبلاً یه کتابخونه کوچیک نوشتم اگر موافق باشید اون رو رو در جایی در پروژه استفاده کنیم با کپی پیست هم راحت میشه دیگه ؛) 
فقط اینکه اگر لطف کنید بگید کجا بنویسم یه فایل باز کنم یا تو یه جای دیگه بنویسم البته اگر موافق این ویژگی بودید:)

**Comment by amirshnll** [comment]
@KomeilParseh 

<br />

برای فیلتر کلمات از این مخزن هم میتونی استفاده کنی :

<br />

[https://github.com/amirshnll/Persian-Swear-Words](https://github.com/amirshnll/Persian-Swear-Words)

**Comment by KomeilParseh** [comment]
> @KomeilParseh
> 
> 
> برای فیلتر کلمات از این مخزن هم میتونی استفاده کنی :
> 
> 
> https://github.com/amirshnll/Persian-Swear-Words

سلام @amirshnll 
بله عالی هستش این ولی اگر چنین چیزی در hazm هم باشه عالی میشه و اینکه این برای پی اچ پی هستش و برای پایتون چنین چیزی موجود نیست و اگر چنین چیزی اینجا هم باشه عالی میشه

**Comment by amirshnll** [comment]
> > @KomeilParseh
> > برای فیلتر کلمات از این مخزن هم میتونی استفاده کنی :
> > https://github.com/amirshnll/Persian-Swear-Words
> 
> سلام @amirshnll
> بله عالی هستش این ولی اگر چنین چیزی در hazm هم باشه عالی میشه و اینکه این برای پی اچ پی هستش و برای پایتون چنین چیزی موجود نیست و اگر چنین چیزی اینجا هم باشه عالی میشه

<div dir="rtl">

من issue ایجاد کردم که برنامه ی این مورد رو سر فرصت تبدیل کنم بله داخا hazm اگر بود که خیلی عالی میشد

</div>
