### ISSUE TITLE
پردازش نکردن متن

### ISSUE THREAD

**Issue by fatemeh75roozbahani** [roshan-research/hazm#211]
سلام ، من wsl رو فعال کردم ، از اوبونتو هم استفاده کردم ، هیچ اروری هم دریافت نمی کنم ، اما خروجی که دریافت میکنم پردازش نشده است و فقط کلماتی که از ابتدا داشتم رو بهم برمی گردونه .خیلی ممنون میشم اگه کسی بتونه راهنمایی کنه .
hi , i turned on the wsl and i used ubuntu too and im not getting any error but the output that im getting is not proccessed and it just giving me the words that i already had , so i would be glad if anyone could giude me , thank you .

**Comment by sir-kokabi** [comment]
آموزش ویدیویی نصب هضم در ویندوز:
https://www.roshan-ai.ir/hazm/docs/
