### ISSUE TITLE
آدرس صحیح پوشه Resources و POSTagger

### ISSUE THREAD

**Issue by Ali-Bazzaz** [roshan-research/hazm#212]
با سلام و وقت بخیر
ببخشید بنده در لینوکس کتابخانه hazm را نصب کردم و تا جایی به خوبی کار کردم ولی هنگام استفاده از پوشه resources به منظور تحلیل صرفی به مشکل خوردم
و میگه که چیزی بنامه POSTagger تعریف نشده یا وجود نداره
module 'POSTagger' not defined
فکر کنم آدرسش درست وارد نشده یا اینکه چیزی این وسط ناقص هست که خلاصه حل نمیشه
لطفا راهنمایی بفرمایید من اینو نوشتم
 tagger = POSTagger ( model = 'resources/postagger.model' )

در ضمن همه چیز رو نصب کردم

**Comment by ali1400hastam** [comment]
لطفا بفرمایید اگر مثلا پروژه بنده توی دسکتاپ باشه باید Resources و POSTagger را کجا قرار بدم؟

**Comment by SaadullahKarimi** [comment]
سلام علیکم ، شما باید در  قسمت فولدر پروژه تان یک فولدر بنام Resources بسازید. و POSTagger را در آن قرار دهید. یا شما از لینک ذیل https://github.com/sobhe/hazm/releases/download/v0.5/resources-0.5.zip فولدر را دانلود کرده -resources-0.5.zip  را توسط  Rename  به Resource تبدیل کنید البته بعد از  Extract zip   و در فولدر Project  تان کاپی و پست نماید ممنون.

**Comment by sir-kokabi** [comment]
احتمالاً آموزش ویدیویی نصب هضم بتونه به شما کمک کنه:
https://www.roshan-ai.ir/hazm/docs/
