### ISSUE TITLE
دقت ترین  POSTagger

### ISSUE THREAD

**Issue by nafarieh** [roshan-research/hazm#221]
با سلام  و خداقوت
دقت ترین  Posttagger  رو  میشه بفرمائید؟
تشکر

**Comment by kokabi1365** [comment]
سلام.
بیشتر توضیح می‌دید؟ 🤔

**Comment by imani** [comment]
سلام
همانطور که در [README](https://github.com/roshan-research/hazm/blob/master/README.md) هضم نوشته شده، دقت ابزار POS Tagger 97.1% در معیار F1 هست.
