### ISSUE TITLE
کرش شدن بعد از اجرای POSTagger

### ISSUE THREAD

**Issue by aliamiri1380** [roshan-research/hazm#233]
بعد از اجرای این دو خط کد سرورم کرش میشه

import hazm
hazm.POSTagger(model='resources/postagger.model')

و اگه آدرس دهی نکنم ارور زیر رو میده

ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by sir-kokabi** [comment]
<div dir="rtl">
از ویندوز استفاده می‌کنید یا لینوکس؟

آیا مدل‌ها رو جداگانه دانلود و اضافه کردید؟
کمی بیشتر دربارهٔ شرایط بروز این خطا بفرمایید.
</div>

**Comment by masoudnick** [comment]
@sir-kokabi 
با سلام
این مشکل کرش کردن روی گوگل کلب و کگل وجود داره!
