### ISSUE TITLE
Crash after tagger.tag

### ISSUE THREAD

**Issue by mjmaher987** [roshan-research/hazm#240]
با سلام و وقت بخیر.
در هنگام استفاده از هضم، مطابق با داکیومنتیشن پیش میروم اما هنگامی که دستور زیر را میزنم session کرش میکنه. از کولب استفاده میکنم.
البته یکی دو بار قبلا تونسته بودم به درستی اجرا کنم اما الان که مجدد همان فایل را در کولب اجرا میکنم و پیش نیازها را هم نصب میکنم به ارور میخوره:
tagger.tag ( word_tokenize( 'ما بسیار کتاب می‌خوانیم' ))

**Comment by sir-kokabi** [comment]
<div dir="rtl">
سلام.

لطفاً کدی که اجرا کردید رو ارسال کنید.
</div>

**Comment by mjmaher987** [comment]
مطابق با کدهای سایت اصلی (https://www.roshan-ai.ir/hazm/) پیش رفتم:
pip install hazm
from __future__ import unicode_literals
from hazm import *
normalizer = Normalizer()
normalizer.normalize ( 'اصلاح نویسه ها و استفاده از نیم فاصله پردازش را آسان می کند' )

sent_tokenize ( 'ما هم برای وصل کردن آمدیم! ولی برای پردازش، جدا بهتر نیست؟' )
#[ 'ما هم برای وصل کردن آمدیم!' , 'ولی برای پردازش، جدا بهتر نیست؟' ]
word_tokenize ( 'ولی برای پردازش، جدا بهتر نیست؟' )
#[ 'ولی', 'برای', 'پردازش'، '،'، 'جدا', 'بهتر', 'نیست', '؟' ]
stemmer = Stemmer()
stemmer.stem ( 'کتاب ها' )
#'کتاب'
lemmatizer = Lemmatizer()
lemmatizer.lemmatize ( 'می روم' )
#'رفت#رو'
tagger = POSTagger ( model = 'resources/postagger.model' )
tagger.tag ( word_tokenize( 'ما بسیار کتاب می‌خوانیم' ))
#[ ( 'ما' , 'PRO' ), ( 'بسیار' , 'ADV' ), ( 'کتاب' , 'N' ), ( 'می خوانیم' , 'V' ) ]
chunker = Chunker( model= 'resources/chunker.model' )
tagged = tagger.tag ( word_tokenize( 'کتاب خواندن را دوست داریم' ))
tree2brackets( chunker.parse (tagged))
#'[کتاب خواندن NP] [را POSTP] [دوست داریم VP]'
parser = DependencyParser (tagger = tagger, lemmatizer = lemmatizer )
parser.parse (  word_tokenize( 'زنگ‌ها برای که به صدا درمی‌آید؟' ))
#<DependencyGraph with 8 nodes>

**Comment by mjmaher987** [comment]
![image](https://user-images.githubusercontent.com/77095635/214998584-59c48295-63f1-4c3f-8ea9-7ab64ce3eec2.png)
تصویر بالا نیز کرش کردن آن در کولب است.

**Comment by sir-kokabi** [comment]
سلام. 
من الان تست کردم. روی کولب کرش کرد. البته روی لوکال مشکلی نبود. فقط روی کولب این اتفاق می‌افته و ظاهراً خطای حافظه است. اگر اصرار دارید روی کلود کدها رو اجرا کنید بد نیست روی سرویس‌های دیگه‌ای به جز کولب هم امتحان کنید. درهرحال مشکلی که به وجود اومده مربوط به کتابخانه نیست. ضمناً مثال‌ها رو از [داکیومنت هضم](https://www.roshan-ai.ir/hazm/docs
) بگیرید که متناسب با آخرین تغییرات کد بروزرسانی می‌شه.

**Comment by sir-kokabi** [comment]
این مشکل در نسخه 0.9 وجود نداره.
