### ISSUE TITLE
words-list can't be found

### ISSUE THREAD

**Issue by Ainaz-vazir** [roshan-research/hazm#241]
درود بعد از نصب بی ارور هضم و وابسته هاش، در زمان ایمپورت*:
cannot import name 'words_list' from 'hazm.utils' (/usr/local/lib/python3.8/dist-packages/hazm/utils.py)

**Comment by sir-kokabi** [comment]
<div dir="rtl">
سلام.

لطفاً کدی که این خطا رو ایجاد کرده ارسال کنید.
</div>
