### ISSUE TITLE
AttributeError: module 'inspect' has no attribute 'formatargspec'

### ISSUE THREAD

**Issue by m-shahrestani** [roshan-research/hazm#259]
سلام
هنگام import hazm خطای  AttributeError: module 'inspect' has no attribute 'formatargspec' داده می‌شود.
ورژن Python 3.11، سیستم‌عامل Windows 10 و محیط اجرای Jupyter notebook.

خطای کامل:

![App 
](https://s2.uupload.ir/files/error_g2fe.png)

**Comment by sir-kokabi** [comment]
احتمالاً این مشکل با نصب ورژن بالاتر nltk حل بشه.
`pip install nltk==3.6.7`

لطفاً نتیجه رو گزارش بدید.

**Comment by m-shahrestani** [comment]
بله ممنون.
با نصب ورژن بالاتر nltk مشکل حل شد.

**Comment by m-shahrestani** [comment]
بله ممنون.
با نصب ورژن بالاتر nltk مشکل حل شد.
