### ISSUE TITLE
نحوه اجرای word embedding و فایل‌های مورد نیاز در resources

### ISSUE THREAD

**Issue by amirkazi99** [roshan-research/hazm#267]
سلام
وقت بخیر. در مورد اجرای word embedding سوال داشتم. آیا مستقیما روی ویندوز خروجی میده؟ و این که یک مثال از کد و خروجی اون به صورت دقیق‌تر می‌شه بزنید؟
تشکر

**Comment by sir-kokabi** [comment]
سلام.
کدهایی که الان روی master هست روی ویندوز اجرا می‌شه.
مثالش اینجا هست:
https://www.roshan-ai.ir/hazm/docs/content/modules/embedding/

**Comment by sir-kokabi** [comment]
سلام.
بله نسخهٔ 0.9  هضم که اخیراً منتشر شده امکان اجرا روی ویندوز رو داره.
برای دیدن مثال‌ها به مستندات مراجعه کنید.
