### ISSUE TITLE
اشکال ریشه‌یابی کلمات سه‌حرفی

### ISSUE THREAD

**Issue by M-Hatami** [roshan-research/hazm#268]
سلام و ممنون برای برنامه خوبتون،

یک اشکالی که من میبینم این است که علیرغم اینکه ریشه اکثر کلمات بدرستی درمیاید، اما بسیاری از کلمات (غالباً اسامی) سه‌حرفی که حرف آخر آنها یکی از حروف **م**، **ی**، **ت**، یا **ش** هستند تغییر میکنند. چند مثال:

آدم
آلی
برش
بزم
بنی
بوم
پخت
پخش
پرت
پری
پشت
پشم
ترش
تقی
تنش
جرم
رزم
ملی

البته مثالهای بیشتری هست، ولی به همین بسنده میکنم.

**Comment by sir-kokabi** [comment]
سلام.
استمر، دقت رو فدای سرعت کرده و به‌همین‌خاطر، ناچار به پیروی از برخی از قواعد ساده مثلاً حذف برخی از پیشوندها و پسوندها است که مسلماً همراه با خطا است. برای ریشه‌یابی دقیق‌تر از [`Lemmatizer`](https://www.roshan-ai.ir/hazm/docs/content/modules/Lemmatizer/#hazm.Stemmer) استفاده کنید. لماتایزر به‌سبب استفاده از لیست کلمات، دقتش بسیار بیشتر از استمره و البته سرعتش از استمر کمتره.

**Comment by M-Hatami** [comment]
سلام از ماست، ممنون برای پاسختون.
لطف کردی وقت گذاشتی و راهنمایی فرمودی، ان‌شاءالله امتحانش میکنم 
مخلصم

**Comment by M-Hatami** [comment]
سلام علیکم آقای کوکبی، فقط خواستم تشکر کنم که بی ادبی نباشه، این خیلی کمک کرد. ممنون
