### ISSUE TITLE
خطا هنگام استفاده از Embedding

### ISSUE THREAD

**Issue by ali-totem** [roshan-research/hazm#273]
سلام من حین استفاده از Embedding با خطای 
**NameError: name 'WordEmbedding' is not defined**
روبرو میشم
یه کد ساده به صورت زیر زدم
```
from hazm import *
wordEmbedding = WordEmbedding(model_type = 'fasttext')
```

Python Version: 3.8.8

**Comment by sir-kokabi** [comment]
سلام.
نسخهٔ 0.9 هضم منتشر شده. 
لطفاً با این نسخهٔ امتحان کنید.

**Comment by amirkazi99** [comment]
با این نسخه هم من هم‌چنان این مشکل رو دارم. در ضمن طبق همون دستوری که گذاشته بودید مدل pos_tagger رو از داکیومنت گیت‌هاب (pretrained models) دانلود کردم و داخل پوشه resources در کنار ریشه پروژه گذاشتم، اما متاسفانه باز هم ارور no models named pos_tagger مشاهده می‌شه

**Comment by sir-kokabi** [comment]
من الان تست کردم خطایی وجود نداشت. از چه نسخه‌ای از پایتون و pip استفاده می‌کنید؟
مطمئن هستید با دستور pip install hazm بدون هیچ خطایی هضم رو نصب کردید؟

**Comment by ali-totem** [comment]
آقای کوکبی ورژن پایتون شما چند هست؟

**Comment by amirkazi99** [comment]
ورژن پایتون من 3.8.10 هستش. بله دستور بدون خطا نصب می‌شه. الان pos_tagger درست شد.

**Comment by sir-kokabi** [comment]
> ورژن پایتون من 3.8.10 هستش. بله دستور بدون خطا نصب می‌شه. الان pos_tagger درست شد.

خطای WordEmbedding حل شد یا نه؟ البته شما اینجا مدل رو لود نکردید ولی این خطایی که می‌بینم به مدل ربط نداره. اصلاً ماژول رو نشناخته و این عجیبه.

**Comment by amirkazi99** [comment]
> 

مشکل امبدینگ نه متاسفانه. 
در حال حاضر دو تا مشکل دارم:
1) https://github.com/roshan-research/hazm/issues/273#issuecomment-1557084112

از داکیومنت گیت هاب مدل dependency parser رو مطابق تصویر دانلود کردم و فایل langModel.mco رو داخل پوشه resources گذاشتم. اما متاسفانه هنگام فراخوانی parser.parse با خطای زیر رو به رو می‌شم:
<img width="439" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/da45e124-9ba1-4914-9876-379086dbc7fb">


2) برای لود مدل wordembedding طبق تصویر زیر باید عمل کنیم؟

<img width="599" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/878c5786-b28a-46b2-bd91-69dce17a0143">


در این صورت فایل cc.fa.300.bin رو از کجا باید دانلود کنیم و داخل پوشه resources بذاریم؟ هم چنین فایل dataset.txt رو از کجا باید دانلود کنیم؟

خطایی که مشاهده می‌شه:

<img width="743" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/807bf3e3-d839-4745-bb25-723cf2e89615">

<img width="647" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/b6189504-3370-4436-b3ec-08ebe7f4b602">
<img width="505" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/ca94fc7a-a3b7-4394-a8ae-03a6cfd6cc94">

**Comment by sir-kokabi** [comment]
فایل` cc.fa.300.bin` چون حجمش بالاست دنبال جای مناسبی برای آپلودش هستیم.
فعلاً از اینجا دانلود کنید مشکل امبیدینگ برطرف می‌شه:
https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fa.300.bin.gz
بعد از دانلود فایل bin داخلش رو در فولدر resources‌ قرار بدید. مقداری خروجی رو با تأخیر می‌ده باید صبر کنید.

در مورد dependecy_parser کدی که روی سیستم شما خطا می‌ده رو برام بفرستید. چون اینجا من تست می‌کنم مشکلی نیست.
در مورد dataset.txt بررسی می‌کنم بهتون خبر می‌دم.

شما این‌ها رو روی کولب تست می‌کنید؟

**Comment by amirkazi99** [comment]
> فایل` cc.fa.300.bin` چون حجمش بالاست دنبال جای مناسبی برای آپلودش هستیم. فعلاً از اینجا دانلود کنید مشکل امبیدینگ برطرف می‌شه: https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.fa.300.bin.gz بعد از دانلود فایل bin داخلش رو در فولدر resources‌ قرار بدید. مقداری خروجی رو با تأخیر می‌ده باید صبر کنید.
> 
> در مورد dependecy_parser کدی که روی سیستم شما خطا می‌ده رو برام بفرستید. چون اینجا من تست می‌کنم مشکلی نیست. در مورد dataset.txt بررسی می‌کنم بهتون خبر می‌دم.
> 
> شما این‌ها رو روی کولب تست می‌کنید؟

parser = DependencyParser(tagger=tagger, lemmatizer=lemmatizer)
parser.parse(word_tokenize('زنگ‌ها برای که به صدا درمی‌آید؟')) این کد همونیه که داخل سایت روشن هست
روی ژوپیتر نوت‌بوک امتحان می‌کنم.

**Comment by sir-kokabi** [comment]
کد مربوط به tagger هم بذارید.
اسم مدل از postagger.model به pos_tagger.model تغییر پیدا کرده.
`tagger = POSTagger(model='resources/pos_tagger.model')`
ما این صفحه رو هنوز بروزرسانی نکردیم. مثال‌ها رو از داکیومنت‌ها و ردمی گیتهاب بردارید.

**Comment by amirkazi99** [comment]
> کد مربوط به tagger هم بذارید. اسم مدل از postagger.model به pos_tagger.model تغییر پیدا کرده. `tagger = POSTagger(model='resources/pos_tagger.model')` ما این صفحه رو هنوز بروزرسانی نکردیم. مثال‌ها رو از داکیومنت‌ها و ردمی گیتهاب بردارید. و اینکه کدها رو اول روی سیستم خودتون تست کنید؛ چون اینجوری ممکنه محدودیت‌ها و خطاهای مربوط به پلتفرم‌هایی مثل ژوپیتر نت بوک و کولب کاملاً گمراه‌کننده باشه.

from hazm import *

tagger = POSTagger(model='resources/pos_tagger.model')
print(tagger.tag(word_tokenize('داریم کتاب می‌خونیم')))

فقط مشکل dependency parser بررسی نشد؟

**Comment by ali-totem** [comment]
> > ورژن پایتون من 3.8.10 هستش. بله دستور بدون خطا نصب می‌شه. الان pos_tagger درست شد.
> 
> خطای WordEmbedding حل شد یا نه؟ البته شما اینجا مدل رو لود نکردید ولی این خطایی که می‌بینم به مدل ربط نداره. اصلاً ماژول رو نشناخته و این عجیبه.

مشکل من برطرف شد
پایتون رو به 3.9 downgrade کردم و hazm رو upgrade کردم درست شد

**Comment by amirkazi99** [comment]
> > > ورژن پایتون من 3.8.10 هستش. بله دستور بدون خطا نصب می‌شه. الان pos_tagger درست شد.
> > 
> > 
> > خطای WordEmbedding حل شد یا نه؟ البته شما اینجا مدل رو لود نکردید ولی این خطایی که می‌بینم به مدل ربط نداره. اصلاً ماژول رو نشناخته و این عجیبه.
> 
> مشکل من برطرف شد پایتون رو به 3.9 downgrade کردم و hazm رو upgrade کردم درست شد

سلام میشه لطفا کدی که تونستید از embedding خروجی بگیرید رو بفرستید؟

**Comment by ali-totem** [comment]
> > > > ورژن پایتون من 3.8.10 هستش. بله دستور بدون خطا نصب می‌شه. الان pos_tagger درست شد.
> > > 
> > > 
> > > خطای WordEmbedding حل شد یا نه؟ البته شما اینجا مدل رو لود نکردید ولی این خطایی که می‌بینم به مدل ربط نداره. اصلاً ماژول رو نشناخته و این عجیبه.
> > 
> > 
> > مشکل من برطرف شد پایتون رو به 3.9 downgrade کردم و hazm رو upgrade کردم درست شد
> 
> سلام میشه لطفا کدی که تونستید از embedding خروجی بگیرید رو بفرستید؟

سلام

```
from hazm import *
wordEmbedding = WordEmbedding(model_type = 'fasttext')
wordEmbedding.load_model('resources/cc.fa.300.bin')
wordEmbedding.doesnt_match(['سلام' ,'درود' ,'خداحافظ' ,'پنجره'])
```

دقیقا کدی که تو سایت هست استفاده کردم

فکر کنم شما باید فایلی که دارید کد میزنید رو حتما save کنید و تو اون مسیر resources/cc.fa.300.bin رو قرار بدید


![image](https://github.com/roshan-research/hazm/assets/5319142/a8cd6503-67a5-46df-a687-aa4ed7c9a8ed)
