### ISSUE TITLE
نسخه 0.9 هضم

### ISSUE THREAD

**Issue by amirkazi99** [roshan-research/hazm#275]
با سلام،
وعده داده بودید نسخه 0.9 این هفته به همراه داکیومنت‌ها منتشر می‌شه. منتشر شده آیا؟ و این که دقیقا چه ویژگی‌ها و قابلیت‌هایی به نسخه‌ی 0.9 اضافه یا افزوده شده؟
سپاس

**Comment by sir-kokabi** [comment]
سلام.
نسخهٔ 0.9 منتشر شده می تونید تغییراتش رو ببینید.
https://pypi.org/project/hazm/

**Comment by amirkazi99** [comment]
<img width="472" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/e0d25125-3ed3-4bcf-ac93-4a1c296cc192">
<img width="641" alt="image" src="https://github.com/roshan-research/hazm/assets/83756179/410f5f4a-af56-4d2f-ac02-e999cf50ff06">
عذر می‌خوام موقع نصب آخرین نسخه به این ارور می‌خورم. مشکل چیه؟

**Comment by sir-kokabi** [comment]
سلام.
با دستور pip install hazm نصب کنید.

**Comment by sir-kokabi** [comment]
من الان رو سیستمم با همین دستور نصب کردم مشکلی نبود. باید بیشتر دربارهٔ شرایط خطا صحبت کنیم.
فعلاً با دستور `pip install hazm` نصب کنید. احتمالاً نباید مشکلی باشه.

**Comment by sir-kokabi** [comment]
لطفاً یکبار pip رو آپگرید کنید و مجدداً نصب کنید.
pip 19‌ و بالاتر نباید این مشکل رو داشته باشه.
