### ISSUE TITLE
تغییرات Pos_tagger

### ISSUE THREAD

**Issue by amirkazi99** [roshan-research/hazm#276]
سلام
در مدل pos_tagger پارامتر دیگری در خروجی ظاهر می‌شود (البته در زمانی که universal فالس باشد.) به عنوان مثال EZ، از طرفی قبلا تک Ne داشتیم که الان نداریم. مستندات مربوط به تغییرات تگ‌های جدید رو از کجا می‌شه مشاهده کرد؟

**Comment by amirkazi99** [comment]
ضمنا تفاوت مدل بونیورسال که دقت بیشتری داره با مدل غیریونیورسال چیه؟ چرا دقت اولی بیشتره؟ لزوم استفاده از مدل دومی چیه؟

**Comment by amirkazi99** [comment]
به نظر می‌رسه برای اندازه‌ی لیست ورودی‌ای که به pos_tagger داده می‌شه، محدودیت وجود داره. من برای بیشتر از لیستی که 262 تا کاراکتر داره نتونستم خروجی بگیرم و با ارور list index out of range رو به رو شدم

**Comment by E-Ghafour** [comment]
سلام وقت بخير 
هنوز مستندی در این رابطه پابلیش نشده و احتمالا این موضوع در بلاگ پست نسخه ۰.۹ هضم توضیح داده میشه.
در کل این تگ Ne که مثال زديد معادل تگ NOUN,EZ در نسخه جدید هستش و عملا تگ e با EZ  جایگزین شده. در نسخه جدید، تگ‌ها به صورت کامل نوشته میشن که به تگ یونیورسال شبیه‌تر باشه. در رابطه با بقیه تگ‌ها هم به همین صورت هست.
تعداد لیبل‌های یونیورسال کمتر از حالت عادی هستش برای همین مدل بهتر میتونه پیشبینی کنه و در نتیجه دقت بیشتری داره. 
به صورت دقيق تر، معادل حالت دیفالت هست ولی تگ EZ نداره و تگ‌ها تنوع کمتری دارند.
برای این تسک POSTagger یکسری لیبل استاندارد وجود داره که بهش میگن یونیورسال.
در رابطه با مورد آخر هم لطفا کدتونو بفرستید تا بيشتر بررسی بشه.

**Comment by amirkazi99** [comment]
خیلی ممنون
کد خاصی نیست:
tagger = POSTagger(model='resources/pos_tagger.model', universal_tag= True)
tagger.tag(StemListAdj)

که در واقع StemListAdj یک لیستی از واژه‌ها است که اندازه‌ی این لیست حدودا 35000 المان بود. ارور اون هم string index out of range بود. وقتی که اندازه‌ی لیست واژه‌ها رو به 262 کاراکتر کاهش دادم، همین کد خروجی داد

**Comment by E-Ghafour** [comment]
وقتی سایز لیست زیاده و  می‌خواهید از این ماجول استفاده کنید با sent_tokenizer, word_tokenizer جملات و کلماتتونو توکنایز کنید و بعد هم با استفاده از tag_sent تگ بزنید.
 اینجوری هم ارور نمیخورید و هم عملکرد مدل خیلی بهتر میشه.

**Comment by amirkazi99** [comment]
> سلام وقت بخير هنوز مستندی در این رابطه پابلیش نشده و احتمالا این موضوع در بلاگ پست نسخه ۰.۹ هضم توضیح داده میشه. در کل این تگ Ne که مثال زديد معادل تگ NOUN,EZ در نسخه جدید هستش و عملا تگ e با EZ جایگزین شده. در نسخه جدید، تگ‌ها به صورت کامل نوشته میشن که به تگ یونیورسال شبیه‌تر باشه. در رابطه با بقیه تگ‌ها هم به همین صورت هست. تعداد لیبل‌های یونیورسال کمتر از حالت عادی هستش برای همین مدل بهتر میتونه پیشبینی کنه و در نتیجه دقت بیشتری داره. به صورت دقيق تر، معادل حالت دیفالت هست ولی تگ EZ نداره و تگ‌ها تنوع کمتری دارند. برای این تسک POSTagger یکسری لیبل استاندارد وجود داره که بهش میگن یونیورسال. در رابطه با مورد آخر هم لطفا کدتونو بفرستید تا بيشتر بررسی بشه.

سلام مجدد
عذر می‌خوام مستندی وجود نداره که این لیبل‌گذاری‌های جدید رو شانل بشه؟
مثلا تو بخش dependency، دیگه obj رو نشون نمی‌ده و فقط  می‌نویسه posdep.
ممنون می‌شم مستندات این قسمت رو به اشتراک بگذارید

**Comment by sir-kokabi** [comment]
اینجا رو ببینید شاید بتونه کمکتون کنه:
https://universaldependencies.org/treebanks/fa_perdt/index.html

**Comment by amirkazi99** [comment]
> اینجا رو ببینید شاید بتونه کمکتون کنه: https://universaldependencies.org/treebanks/fa_perdt/index.html

خیلی ممنون. فقط برای pos هست، درسته؟ برای معرفی dependencyها چی؟ مستندی مثل این (https://github.com/roshan-research/dependency-parse-tree/blob/master/dependency-tree.js) وجود داره آیا؟

**Comment by sir-kokabi** [comment]
نه متاسفانه.
فعلاً معادل فارسی این‌ها رو نداریم و من جای دیگه‌ای هم ندیدم.
داریم روش کار می‌کنیم. در مورد این تگ‌ها واقعاً کمبود جدی اطلاعات هست. امیدواریم با کمک زبان‌شناس‌ها بتونیم در این زمینه مستندات خوبی تهیه کنیم.
