### ISSUE TITLE
خروجی dependency

### ISSUE THREAD

**Issue by amirkazi99** [roshan-research/hazm#282]
با سلام
جمله‌ی «کیفبت خوبی دارد.» رو به دیپندنسی دادم. تو نسخه‌ی جدید خروجی‌های عجیب و اشتباهی می‌ده مثلا:
defaultdict(<function DependencyGraph.init.<locals>.<lambda> at 0x0000020275AD2E50>,
            {0: {'address': 0,
                 'ctag': 'TOP',
                 'deps': defaultdict(<class 'list'>, {'ROOT': [2]}),
                 'feats': None,
                 'head': None,
                 'lemma': None,
                 'rel': None,
                 'tag': 'TOP',
                 'word': None},
             1: {'address': 1,
                 'ctag': 'NOUN',
                 'deps': defaultdict(<class 'list'>, {}),
                 'feats': '_',
                 'head': 2,
                 'lemma': 'کیفیت',
                 'rel': 'PREDEP',
                 'tag': 'NOUN',
                 'word': 'کیفیت'},
             2: {'address': 2,
                 'ctag': 'ADJ',
                 'deps': defaultdict(<class 'list'>,
                                     {'PREDEP': [1],
                                      'PUNC': [3]}),
                 'feats': '_',
                 'head': 0,
                 'lemma': 'خوبی',
                 'rel': 'ROOT',
                 'tag': 'ADJ',
                 'word': 'خوبی'},
             3: {'address': 3,
                 'ctag': 'VERB',
                 'deps': defaultdict(<class 'list'>, {'POSDEP': [4]}),
                 'feats': '_',
                 'head': 2,
                 'lemma': 'دارد',
                 'rel': 'PUNC',
                 'tag': 'VERB',
                 'word': 'دارد'},
             4: {'address': 4,
                 'ctag': 'PUNCT',
                 'deps': defaultdict(<class 'list'>, {}),
                 'feats': '_',
                 'head': 3,
                 'lemma': '.',
                 'rel': 'POSDEP',
                 'tag': 'PUNCT',
                 'word': '.'}})

قبلا relها مشخص‌کننده روابط بین جمله بودند. الان به عنوان مثال برای «دارد» نوشته punc. در صورتی که اصلا جزء علائم نگارشی نیست این فعل!!!

**Comment by amirkazi99** [comment]
> با سلام جمله‌ی «کیفبت خوبی دارد.» رو به دیپندنسی دادم. تو نسخه‌ی جدید خروجی‌های عجیب و اشتباهی می‌ده مثلا: defaultdict(<function DependencyGraph.init.. at 0x0000020275AD2E50>, {0: {'address': 0, 'ctag': 'TOP', 'deps': defaultdict(<class 'list'>, {'ROOT': [2]}), 'feats': None, 'head': None, 'lemma': None, 'rel': None, 'tag': 'TOP', 'word': None}, 1: {'address': 1, 'ctag': 'NOUN', 'deps': defaultdict(<class 'list'>, {}), 'feats': '_', 'head': 2, 'lemma': 'کیفیت', 'rel': 'PREDEP', 'tag': 'NOUN', 'word': 'کیفیت'}, 2: {'address': 2, 'ctag': 'ADJ', 'deps': defaultdict(<class 'list'>, {'PREDEP': [1], 'PUNC': [3]}), 'feats': '_', 'head': 0, 'lemma': 'خوبی', 'rel': 'ROOT', 'tag': 'ADJ', 'word': 'خوبی'}, 3: {'address': 3, 'ctag': 'VERB', 'deps': defaultdict(<class 'list'>, {'POSDEP': [4]}), 'feats': '_', 'head': 2, 'lemma': 'دارد', 'rel': 'PUNC', 'tag': 'VERB', 'word': 'دارد'}, 4: {'address': 4, 'ctag': 'PUNCT', 'deps': defaultdict(<class 'list'>, {}), 'feats': '_', 'head': 3, 'lemma': '.', 'rel': 'POSDEP', 'tag': 'PUNCT', 'word': '.'}})
> 
> قبلا relها مشخص‌کننده روابط بین جمله بودند. الان به عنوان مثال برای «دارد» نوشته punc. در صورتی که اصلا جزء علائم نگارشی نیست این فعل!!!

قبلا  و تو نسخه‌ی قبلی درست بود.
ولی الان نیست

**Comment by amirkazi99** [comment]
سلام مجدد
این باگی که ذکر شد، به خاطر فایل‌های malt.jar و پوشه‌ی libs نیست که توی resources می‌ذاریم؟ چون برای نسخه‌ی جدید فایل malt.jar و پوشه libs نبود، از این دو فایلی که برای نسخه‌ی قبلی گذاشته بودید، استفاده کردم. آیا می‌تونه مشکل به خاطر این موضوع باشه؟ اگر هست، لطفا فایل‌های جدیدی که باید داخل پوشه‌ی resources بذاریم رو به اشتراک بذارید

**Comment by sir-kokabi** [comment]
سلام.
نه از اون نیست.
اون فایل‌ها تغییری نکرده. می‌تونید از اینجا دانلود کنید.
https://github.com/sir-kokabi/resources

**Comment by amirkazi99** [comment]
> سلام. نه از اون نیست. اون فایل‌ها تغییری نکرده. می‌تونید از اینجا دانلود کنید. https://github.com/sir-kokabi/resources

سلام آقای کوکبی
مشکل برطرف نشد؟

**Comment by sir-kokabi** [comment]
این مشکل در نسخه 0.9.2 حل شده.
