### ISSUE TITLE
incorrect stemmer result for word ایران

### ISSUE THREAD

**Issue by mnwato** [roshan-research/hazm#288]
```sh
from hazm import Stemmer

stemmer = Stemmer()
stemmed_token = stemmer.stem('ایران')

print(stemmed_token)
```
> output:: 'ایر'

- Hazm version: 0.9.3

**Comment by sir-kokabi** [comment]
سلام.
ماهیت استمر نه‌تنها در کتابخانهٔ هضم بلکه در تمام کتابخانه‌های nlp همراه با خطا است. دلیلش اینه که در استمر دقت فدای سرعت شده. صرفاً یک سری پسوندها رو حذف می‌کنه که همراه با خطا هست. مثلاً در بالا «ان» نشانهٔ جمع هست که در برخی از کلمات مثل دوستان، دشمنان، درختان، هموطنان، عزیزان و ... مشکلی ایجاد نمی‌کنه ولی در بعضی از کلمات مثل ایران، خیابان، شتابان و ... مشکل ایجاد می‌کنه. لماتایزر برخلاف استمر روی دقت تمرکز داره و چون مبتنی بر لیست کلمات هست اشتباهاتش کمتره.
