### ISSUE TITLE
numpy versien 1.22.4 suport

### ISSUE THREAD

**Issue by smhd001** [roshan-research/hazm#289]
سلام
با توجه به این که تعداد زیادی از افراد از محیط colab استفاده می‌کنند و ورژن دیفالت `numpy` بر روی این محیط `1.22.4` می باشد پشتیبانی از این نسخه می‌تواند نصب `hazm` رو بر روی این محیط خیلی راحت تر کند.

**Comment by sir-kokabi** [comment]
سلام.
متأسفانه به خاطر ناسازگاری کتابخانهٔ gensim‌ با numpy<1.24.x امکان انجام این کار وجود نداره.
