### ISSUE TITLE
No module named 'wapiti'

### ISSUE THREAD

**Issue by Sajjad-Mehrpeyma** [roshan-research/hazm#290]
Hi everyone,
Recently I attended to use Hazm for a Persian NLP task(finding key phrases in a text),
But when I tried to use 'POSTagger' it gave me this error.

>>  from hazm import *
>>  tagger = POSTagger('postagger.model')

No module named 'wapiti'

I installed wapiti3 using 'pip install wapiti3' using Windows CMD.
when I type 'wapiti' in cmd it shows the version and details of wapiti 3:

Wapiti 3.1.7 (wapiti-scanner.github.io)
etc...

What is your suggestion??

**Comment by sir-kokabi** [comment]
شما از کدوم نسخهٔ هضم استفاده می‌کنید؟
در صورت امکان کدی که خطا می‌ده رو روی کولب به اشتراک بگذارید.
کتابخانهٔ Wapiti برای نسخه‌های قدیمی هضم بود. در نسخه‌های جدید از این پکیج استفاده نمیشه.

**Comment by Sajjad-Mehrpeyma** [comment]
هضم رو به جدیدترین نسخه آپدیت کردم و مشکلم حل شد. ممنونم.
