### ISSUE TITLE
Word Embeddings

### ISSUE THREAD

**Issue by Amirlashkar** [roshan-research/hazm#293]
سلام وقت بخیر

میخواستم بدونم حجم داده هایی که word embedding ها ازشون استخراج شده چقدر بوده و در میشه مدل pre-train رو با یسری داده های دیگه fine-tune کرد؟
و اینکه این پروسه رو با word2vec و gensim انجام دادید درسته؟

**Comment by imani** [comment]
سلام بله با gensim این کار انجام شده و البته مدلش fasttext هست و word2vec نیست. مدل‌ها روی ۱۰ درصد از پیکره متنی ناب آموزش داده شده‌اند که حدود 13 گیگابایت داده متنی بوده است.
