### ISSUE TITLE
Conda Env

### ISSUE THREAD

**Issue by p0mad** [roshan-research/hazm#294]
سلام
من از کتابخانه شما داخل کولب استفاده کردم و الان میخوام روی سیستم خودم استفاده کنم ولی به مشکل میخورم!
میتونید یمل فایل قابل استفاده رو قرار بدید؟
conda env export > environment.yml
ممنون

**Comment by p0mad** [comment]
من روی اوبونتو میخوام تستش کنم ولی اگر برای ویندوز هم باشه اوکیه

**Comment by p0mad** [comment]
هضم نیاز به جی پی یو داره؟
اگر با جی پی یو سرعت افزایش پیدا میکنه لطفا هر دو نسخه رو بزارید ( اولویت با جی پی یو)

**Comment by imani** [comment]
سلام هضم نیازی به GPU نداره و صرفا با CPU کار میکنه. پکیج‌های مورد نیاز هضم رو هم میتونید توی requirements.txt ببینید. 
میتونید از این فایل در environment.yml استفاده کنید:
https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
