### ISSUE TITLE
ERROR Incompatible with Python version: 3.11.3 required 3.[9, 10]

### ISSUE THREAD

**Issue by hiraddlz** [roshan-research/hazm#295]
I will get this error while trying to install the hazm on python 3.11 (due to python-crfsuite installation problem):
```
Building wheels for collected packages: python-crfsuite
  Building wheel for python-crfsuite (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\pycrfsuite
      copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-cpython-311\pycrfsuite
      copying pycrfsuite\_logparser.py -> build\lib.win-amd64-cpython-311\pycrfsuite
      copying pycrfsuite\__init__.py -> build\lib.win-amd64-cpython-311\pycrfsuite
      running build_ext
      building 'pycrfsuite._pycrfsuite' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-crfsuite
  Running setup.py clean for python-crfsuite
Failed to build python-crfsuite
ERROR: Could not build wheels for python-crfsuite, which is required to install pyproject.toml-based projects
```

 I downgrade to python 3.10 and installed properly.

**Comment by sir-kokabi** [comment]
سلام.
من الان یک venv ساختم و هضم بدون هیچ مشکلی روی پایتون ۳.۱۱.۳ نصب شد!
![23236](https://github.com/roshan-research/hazm/assets/116794136/9812f1cd-2de8-4122-9e5f-46bc3f4e031a)

**Comment by hiraddlz** [comment]
سلام
خیلی ممنون از پاسختون
متاسفانه همان خطای قبل را میدهد

https://github.com/roshan-research/hazm/assets/83465357/35efa728-3801-4ccb-ac7a-2111fa8de0f3

**Comment by sir-kokabi** [comment]
خیلی عجیبه.
من احتمال دادم از پایتون `3.11.5` باشه چون من روی `3.11.3` تست گرفته بود ولی روی `3.11.5` هم مشکلی ندیدم.
باید فکر کنیم مشکل کجاست. چون از نسخهٔ پایتون و pip نیست. همه چی یکسانه.
![23236](https://github.com/roshan-research/hazm/assets/116794136/685cf9db-f559-4234-8dec-063b08f9cac6)

**Comment by imani** [comment]
سلام طبق خطایی که داده احتمالا باید نسخه‌ جدیدتری از  microsoft Visual c++ build tools رو نصب کنید:
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by sir-kokabi** [comment]
قبل از اینکه C++ Build tools رو نصب کنید که متأسفانه حجم خیلی داره conda‌ رو تست کنید. کاربری اشاره کرده بود که این مشکل رو با virtualenv داشته و با conda مشکل حل شده.
https://stackoverflow.com/a/73248150/20947581

**Comment by hiraddlz** [comment]
بله با conda تونستم نصب کنم. خیلی ممنون

**Comment by MJT369** [comment]
سلام من کتابخانه  parsinorm را نصب کردم مشکل نصب hazm  حل شد  .
