### ISSUE TITLE
ارور نصب کتاب خانه پایتون

### ISSUE THREAD

**Issue by MRXLANTERN** [roshan-research/hazm#297]
سلام کسی میدونه چطور میشه این ارور رو حل کرد وقتی pip install colorma رو میزنم این ارور رو میده

![cmd](https://github.com/roshan-research/hazm/assets/146003439/a53cb481-6763-4fb2-926b-97a5bb0363d5)

**Comment by sir-kokabi** [comment]
سلام.
ظاهراً جای اشتباهی پیام گذاشتید.

**Comment by MRXLANTERN** [comment]
سلام ببخشید من تازه کارم دارم پایتون دوره مستری یاد میگیرم 
کتاب خانه هضم چیه؟؟؟؟
و اگر میتونید ارور من رو رفع کنید لطفا پیام بدید
خیلی خیلی ممنون [sir-kokabi](https://github.com/sir-kokabi)

**Comment by sir-kokabi** [comment]
هضم یک کتابخانه برای پردازش متون فارسی در پایتون هست. 
توضیحات بیشتر رو می‌تونید اینجا بخونید.
https://www.roshan-ai.ir/hazm/
احتمالاً اگر از فیلترشکن استفاده کنید مشکل حل می‌شه.
یک سری دلایل دیگه هم می‌تونه داشته باشه. باید خطا رو سرچ کنید:
https://stackoverflow.com/questions/50305112/pip-install-timeout-issue

با اجازه‌تون من این ایشو رو چون ارتباطی به کتابهٔ هضم نداره می‌بندم.

**Comment by MRXLANTERN** [comment]
خیلی ممنون سپاس از شما❤❤❤
