### ISSUE TITLE
سوال در مورد تگ ها ی pos

### ISSUE THREAD

**Issue by mhdi707** [roshan-research/hazm#303]
سلام میخواستم بپرسم کدام ورژن از هضم  تگ های pos  اش دقیقا با تگ های stanford parser برابر هست یعنی مثلا یه جای CCONJ داشته باشیم CC
نکته دوم در شناسایی parented_tree یک تاپل  (CCONJ,"و") چرا به عنوان یک parented_tree شناسایی نمیشه؟ ممنون

**Comment by imani** [comment]
در مورد برچسب‌های POS برچسب‌های Universal رو پشتیبانی میشه. درنسخه‌های قدیمی‌تر (0.8 و قبل‌تر) یک wrapper برای stanfor pos tagger موجود هست که میتونید با استفاده از مدل از قبل آموزش داده شده با استفاده از این wrapper خروجی‌های stanford رو بگیرید.

در مورد tree ها POSTagger به صورت یک SequenceTagger عمل میکنه و اگر می‌خواهید درخت جمله رو داشته باشید باید از DependencyParser استفاده کنید.

**Comment by mhdi707** [comment]
سلام ممنون از پاسخگوییتون. حقیقتا ورژن را پایین آوردم و با کلی اررور مواجه شدم و منصرف شدم از کار با wrapper استنفورد.
بنده dependency tree  نمی خوام و نیاز به کار با constituency parser  ها دارم ، میخواستم بپرسم چگونه میتوان دقت مدل  chunker  رو بالا برد که  np  ها رو دقیق تر تشخیص بده و احیانا با تابع parse هم خوب کار کنه و بشه ازش خروجی Tree گرفت؟ممنون
