### ISSUE TITLE
مشکل نصب در جوپیتر

### ISSUE THREAD

**Issue by farhadaz24511** [roshan-research/hazm#313]
واقعا نمیشد مثل خیلی از پکیج های دیگر طوری طراحی بشه که کمتر اذیت کنه؟ 
error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [12 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-311
  creating build\lib.win-amd64-cpython-311\pycrfsuite
  copying pycrfsuite\_dumpparser.py -> build\lib.win-amd64-cpython-311\pycrfsuite
  copying pycrfsuite\_logparser.py -> build\lib.win-amd64-cpython-311\pycrfsuite
  copying pycrfsuite\__init__.py -> build\lib.win-amd64-cpython-311\pycrfsuite
  running build_ext
  building 'pycrfsuite._pycrfsuite' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-crfsuite
ERROR: Could not build wheels for python-crfsuite, which is required to install pyproject.toml-based projects

**Comment by sir-kokabi** [comment]
سلام.
اینجا رو نگاه کنید فکر کنم مشکل مشابهی رو داشتن.
#295
