### ISSUE TITLE
ارور هنگام استفاده از «استخراج کلمات کلیدی» 

### ISSUE THREAD

**Issue by mahdiahmadi87** [roshan-research/hazm#333]
سلام،‌ من از نسخه 0.10.0 هضم و 3.11.4 پایتون روی Ubuntu 23.04 استفاده میکنم
هنگامی که میخواستم از [این لینک](https://www.roshan-ai.ir/hazm/docs/content/samples/keyword_extraction.html)،‌ از کد استخراج کلمات کلیدی استفاده کنم، در قسمت `from hazm.Embedding import SentEmbedding` به این ارور خوردم:
```
>>> from hazm.Embedding import SentEmbedding
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'hazm.Embedding'

```
با این که هنگام نصب هضم به هیچ مشکلی بر نخوردم و تمام ماژول های دیگر را نیز نصب کردم، به این ارور خوردم

**Comment by imani** [comment]
سلام
حرف اول به اشتباه داخل مستندا بزرگ نوشته شده. این‌طور بنویسید:
from hazm.embedding import SentEmbedding

لطفا این بخش رو در مستندات اصلاح کنید. @sir-kokabi 

> سلام،‌ من از نسخه 0.10.0 هضم و 3.11.4 پایتون روی Ubuntu 23.04 استفاده میکنم هنگامی که میخواستم از [این لینک](https://www.roshan-ai.ir/hazm/docs/content/samples/keyword_extraction.html)،‌ از کد استخراج کلمات کلیدی استفاده کنم، در قسمت `from hazm.Embedding import SentEmbedding` به این ارور خوردم:
> 
> ```
> >>> from hazm.Embedding import SentEmbedding
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'hazm.Embedding'
> ```
> 
> با این که هنگام نصب هضم به هیچ مشکلی بر نخوردم و تمام ماژول های دیگر را نیز نصب کردم، به این ارور خوردم
