### ISSUE TITLE
تشخیص سوالی بودن جمله

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [roshan-research/hazm#68]
سلام
 راهی هست تشخیص بدیم جمله سوالیه یا خبری یا تعجبی ؟

ممکنه جمله ی ورودی علامت سوال و .. نداشته باشه

**Comment by nournia** [comment]
<div dir=rtl>
سلام
در هضم راه هوشمندانه‌ای برای این کار تعریف نشده.
می‌تونید فهرستی از واژه‌های پرسشی تهیه کنید و بر اساس اونها جمله‌های سوالی رو پیدا کنید.

**Comment by alirezaafzalaghaei** [comment]
تشخیص مثبت یا منفی بودن جمله چی؟ اینم نداره؟

اگه امکانش هست این ویژگی ها رو به ماژول اضافه کنید. برای مکالمه خیلی به درد میخره:)

**Comment by nournia** [comment]
<div dir=rtl>
متاسفانه فعلا نداریم.
