### ISSUE TITLE
فهرست رسمی املای لغت‌های فارسی

### ISSUE THREAD

**Issue by reza1615** [roshan-research/hazm#80]
سلام
فرهنگستان در [اینجا ](http://www.persianacademy.ir/fa/X220995.aspx)[کتاب املای فارسی](http://www.persianacademy.ir/UserFiles/File/fe1394.pdf) را ارائه داده است که املای اکثر لغت‌‌های فارسی را پوشش می‌دهد شاید این فهرست به درد ابزار شما بخورد.

**Comment by nournia** [comment]
<div dir=rtl>
ممنون، فهرست کاملیه.

**Comment by dariubs** [comment]
سلام.
این لیست در قالب یک دیتاست قابل استفاده بصورت متن در دسترس نیست؟

**Comment by reza1615** [comment]
متاسفانه فقط همین پی‌دی‌اف را ارائه دادند و باید خودمان فایل متنی را تهیه کنیم

**Comment by reza1615** [comment]
سلام فایل متنی را پیوست کردم امیدوارم به دردتان بخورد
[FarsiWords.txt](https://github.com/sobhe/hazm/files/755430/FarsiWords.txt)

**Comment by reza1615** [comment]
نسخهٔ تمیز شدهٔ فایل قبلی را هم اینجا می‌گذارم تا برایتان دوبارکاری نشود
[FarsiWords-cleaned version.txt](https://github.com/sobhe/hazm/files/755509/FarsiWords-cleaned.version.txt)

**Comment by ahangarha** [comment]
<p dir="rtl">
یک ایراد بزرگ وجود داره: تمام نیم‌فاصله‌ها حذف شده‌اند و مثلا کلمه «یگانه‏‌پرست» تبدیل شده به «یگانه‏پرست» که قابل استفاده نیست.
</p>

**Comment by moosayaghmaiee** [comment]
فایل زرنگار را پیدا کردم و اینجا پیوست می کنم

چون گیت هاب فایل بدون پسوند را قبول نمی‌کند آن را 
txt 
کردم برای بازکردن یا تبدیل کردن باید پسوند  را بردارید
[zarnegar.txt](https://github.com/sobhe/hazm/files/757108/zarnegar.txt)

**Comment by ahangarha** [comment]
من نمی‌تونم این فایل رو درست باز کنم

**Comment by nournia** [comment]
<div dir=rtl>

بسیار عالی.
امیدوارم بتونیم یک نسخه بی‌اشکال ازش تهیه کنیم.
