### ISSUE TITLE
Docx خواندن محتویات اسناد

### ISSUE THREAD

**Issue by barooni69** [roshan-research/hazm#84]
سلام 

برای دریافت محتویات یه سند با فرمت داک ایکس  و دادن محتویات آن به نرمالایز بنده مشکل دارم  نمیدپنم چطور محتویاتشو بهش بدم

برای خوندن یه فایل داک ایکس از کتابخانه زیر استفاده کردم
python-docx

لطفا راهنماییم کنید

با تشکر

**Comment by nournia** [comment]
<div dir=rtl>
سلام

محتوی فایل شما xml هست. باید با استفاده از یک کتابخانه مناسب برای پردازش این نوع فایل، مثل pyquery یا کتابخانه‌های خوب دیگه، هر بخش از نوشته رو پیدا کنید و اون رو به دست نرمالایزر بدید.
البته جزء توسعه‌های آینده قرار هست که هضم بتونه این نوع نوشته رو نرمال کنه ولی فعلا باید فقط متن رو دریافت کنه و نه xml.
