### ISSUE TITLE
مشکل در نصب 

### ISSUE THREAD

**Issue by bakhooleh** [roshan-research/hazm#87]
سلام ممنون از پکیج خوبتون ، من نیاز شدیدی به پکیح شما برای کارای پایان نامه م دارم ولی تو نصبش دچار مشکل شدم میشه لطفا راهنماییم کنین؟

 cwapiti/src/bcd.c(30) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory
    error: command 'C:\\Users\\user\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

یه چنین خطایی به من میده موقع نصب هضم ، مشکل از نسخه ویندوز10  من هست یا باید یه سری پکیجای دیگه نصب کنم؟

**Comment by nournia** [comment]
<div dir=rtl>

لطفا نگاهی به بخش نصب در سایت بندازید که برای نصب روی ویندوز هم راهکار داره.

**Comment by fardi123** [comment]
سلام.چرا به طور واضح کسی نمی گه چطور نصب کنم؟
من اوبونتو دارم و پایتون 2.7 رو نصب کرده ام.
بسته ها رو هم دانلود کرده ام
آناکاندا رو نمی خوام نصب کنم. 
آیا راهی وجود ندارد با استفاده از دستور pip 
این بسته ها را از طریق ترمینال نصب کنم؟
مثال بزنید لطفا
ثواب دارد
pip install ........

**Comment by nournia** [comment]
<div dir= auto>

سلام
مگر این دستور کار نمی‌کنه؟

    sudo pip install hazm

**Comment by bakhooleh** [comment]
سلام، منم همین مشکل و داشتم و دارم!  این بسته رولینوکس نصب میشه ولی رو
ویندوز مشکل داره بدم مشکل داره، متاسفانه درست و دقیق توضیح ندادن دوستان،
منم دیگه بیخیالش شدم با اینکه خیلی هم نیاز داشتم!

**Comment by bakhooleh** [comment]
سلام، منم همین مشکل و داشتم و دارم!  این بسته رولینوکس نصب میشه ولی رو
ویندوز مشکل داره بدم مشکل داره، متاسفانه درست و دقیق توضیح ندادن دوستان،
منم دیگه بیخیالش شدم با اینکه خیلی هم نیاز داشتم!

**Comment by sajaddp** [comment]
@nournia 
شاید مناسب تر باشه که تیم محترم توسعه دهنده برای موضوع هضم در ویندوز زمان بگذارند و دقیق تر بررسی کنند.
احتمالا عدم وجود کتاب خانه خاصی در نسخه های جدید کامپایلرهای ویژوال یا همگام نشدن با نسخه های جدید nltk و یا تغییر نوع کدها به علت بروزرسانی هسته ی پایتون باعث این موضوع شده.
افراد بسیار در هنگام نصب نسخه 0.5
با خطایی مانند Cannot open include file
مواجه می شوند که حاکی از عدم وجود پیش نیاز خاصی هست.
این در حالی رخ میده که در نسخه 0.4 چنین مسئله ای وجود نداره و قطعا با بررسی دقیق تیم توسعه دهنده قابل حل هست به خصوص اینکه پایتون ذاتا وابستگی به سیستم عامل نداره و ماژول ها در سیستم های عامل های مختلف باید عملکرد یکسانی داشته باشند.

**Comment by nournia** [comment]
<div dir=rtl>

دلیل وجود مشکل در ویندوز این هست که ما برای افزایش سرعت از یک ابزار CRF استفاده کردیم که کدهای C داره.
نصب [این ابزار](https://github.com/adsva/python-wapiti) روی ویندوز کار سختی هست. برای همین هم در راهنمای نصب توصیه کردیم که از ویژگی جدید ویندوز استفاده کنید که لینوکس رو در ویندوز اجرا می‌کنه. من با این ویژگی هضم رو در ویندوز خیلی آسون با یک دستور pip نصب کردم.

**Comment by hatamiarash7** [comment]
برای نصب و استفاده روزی وینوز میشه از WSL استفاده کرد
ولی خب واقعا فرقی با لینوکس نداره ... اگه بشه به صورت معمول توی ویندوز ازش استفاده کرد خیلی عالی میشه
لطفا یه فکری براش کنید

برای مثال اولین مشکلی که به وجود میاد وقتیه که میخوایم با پایتون رابط کاربری ایجاد کنیم برای برنامه مون. رابط کاربری tkinter توی لینوکس از زبان فارسی و rtl به خوبی پشتیبانی نمیکنه و خیلی مشکلات هست
رابط کاربری توی ویندوز مشکلی نداره ولی از این طرف هضم نصب نمیشه

واقعا اگر امکانش هست این مشکل رو درست کنید
تشکر

**Comment by nournia** [comment]
<div dir=rtl>

خب الان یه مقدار مشکل هست انجام این کار.
البته واسط گرافیک با پایتون چیز خوبی در نمیاد کلا و بهتره برید سراغ واسط وب که هضم هم جواب می ده :)

**Comment by zinasir** [comment]
سلام
من ویندوزم 8.1 هست
wsl رو نمیتونم فعال کنم 
باید حتماً ویندوز 10 نصب کنم؟

**Comment by nournia** [comment]
<div dir=rtl>

سلام
این ویژگی نسخه‌های جدید ویندوز ۱۰ به خوبی پشتیبانی می‌شه.

**Comment by zinasir** [comment]
غیر از نصب ویندوز 10 راه حل دیگه ای نداره؟

**Comment by nournia** [comment]
<div dir=rtl>

می‌تونید از لینوکس یا مک استفاده کنید و یا اینکه نسخه‌های قبلی هضم رو نصب کنید.

**Comment by sajaddp** [comment]
@zinasir 
متاسفانه همچنان یکی از ایرادات بزرگ هضم وابستگی به سیستم عامل های خاص هست
یک مجازی ساز نصب کنید و درونش لینوکس نصب کنید.

**Comment by zinasir** [comment]
با cygvin نمیشه نصب کرد؟

**Comment by nournia** [comment]
<div dir=rtl>

می‌شه، ولی فکر می‌کنم برای شما خیلی مشکل باشه.

**Comment by zinasir** [comment]
من اوبونتو نصب کردم و مشکل قبلی حل شد.
اما کد postagger خیلی کند اجرا میشه
در صورتی که ریشه یابی و غیره سرعت خوبی داره.
فولدر resorces رو داخل فولدر پروژم قرار دادم.

**Comment by samiava** [comment]
سلام من نسخه 0.5 هضم رو که میخام نصب کنم خطای زیر رو میده چکار باید کنم 
failed building wheel for libwapiti
بعدش هم اینو نشون میده 
![21212](https://user-images.githubusercontent.com/39841430/40862185-ea12900e-6600-11e8-89d6-ba140cc2a024.png)

**Comment by hatamiarash7** [comment]
@samiava 
شماهم داری رو ویندوز نصب میکنی کتابخانه رو
کامنت های قبلی رو بخونید راه حال هایی براش ذکر شده

* مجازی سازی
* WLS
* لینوکس / مک

روی ویندوز در حالت عادی واقعا اذیت میشید بخواید نصب کنید یا کار کنید با این کتابخانه

**Comment by zohreh3906** [comment]
سلام من در نصب هضم در ویندوز به مشکل زیر برخوردم. میشه راهنمایی بفرمایید
![image](https://user-images.githubusercontent.com/37498680/50753318-c013d480-1266-11e9-89bd-fd0c0aad9f4b.png)

**Comment by alisharifi2000** [comment]
> 
> 
> سلام من در نصب هضم در ویندوز به مشکل زیر برخوردم. میشه راهنمایی بفرمایید
> ![image](https://user-images.githubusercontent.com/37498680/50753318-c013d480-1266-11e9-89bd-fd0c0aad9f4b.png)

سلام برای حل این مشکل اگر از ویندوز 10 استفاده میکنید . میتوانید از قابلیت
WSL -> windows sub linux 
استفاده کنید که دستور اجرای کردن آن در اینترنت موجود است و شاید اگر نگاه کنید از توضیحات بنده بهتر باشد . بعد از نصب شما به یک محیط همانند 
cmd 
خواهید داشت که در محیط ابونتو یا هرتوزیع دلخواه دیگری مثل دیبیان، کالی لینوکس میباشد . سپس در آن محیط به فولدر مورد نظر بروید و کد های خود را ران کنید مشکلاتان حل میگردد . اما اگر از ویندوزی به غیر از 10 استفاده میکنید متاسفانه فکر نکنم راه حلی به جز نصب سیستم عامل لینوکس داشته باشید . اگر بازهم سوالی داشتید میتوانید همین جا بپرسید اگر قادر به پاسخ گویی بودم حتما خدمتتان میگم .

**Comment by aminzm** [comment]
سلام دوستان معادل دستور tree2conlltags در nltk دستور زیر است؟ 
tagger = IOBTagger(patterns=['*', 'U:word-%x[0,0]', 'U:word-%x[0,1]'])
tagger.train([[('من', 'PRO', 'B-NP'), ('به', 'P', 'B-PP'), ('مدرسه', 'N', 'B-NP'), ('رفته_بودم', 'V', 'B-VP'), ('.', 'PUNC', 'O')]])
tagger.tag_sents([[('من', 'PRO'), ('به', 'P'), ('مدرسه', 'N'), ('رفته_بودم', 'V'), ('.', 'PUNC')]])
output:
[[('من', 'PRO', 'B-NP'), ('به', 'P', 'B-PP'), ('مدرسه', 'N', 'B-NP'), ('رفته_بودم', 'V', 'B-VP'), ('.', 'PUNC', 'O')]]
اگه اینه میخواستم ببینم پیکره اموزشی برای این کدام پیکره است؟تشکر
------------------------------------------------------------
سوال دوم هم اینه که میخوام یه چانکر با regular expression مثل دستور زی بزنم تو هضم باید از کدوم دستور استفاده کنم؟
"(<JJ>* <NN.*>+ <IN>)? <JJ>* <NN.*>+"

**Comment by abmadani** [comment]
سلام 
یک مشکلی که من با پکیج داشتم واسه نصبش داخل مک بود و احتمالا لینوکسی ها هم این مشکل و داشتن، وقتی میبینید نمیتونید با دستور 
`pip`
 نصب کنید. 
در فایل
`setup.py` 
رفته و خط ۲۹ رو با هشتگ کامنت کنید.
