### ISSUE TITLE
مشکل استمر با برخی از واژه ها

### ISSUE THREAD

**Issue by janamhosein** [roshan-research/hazm#99]
<div dir="rtl">باسلام،
با تشکر از کار ارزشمند گروه شما.
1- استمر شما در مواجه با واژه هایی مانند "ایشان" به خطا می خورد البته به شرطی که از لیست استاپ ورد استفاده نشود. به دلیل اینکه تمام حرف های این واژه در ترتیب پسوندها قرار گرفته و حذف می شوند البته بنده برای جلوگیری از این مشکل یک شرط اضافه کردم به استمر که حداقل طول کلمه را یک درنظر می گیرد و بیشتر از آن حذف نمی کند و در نهایت تک واژه "ا" برمیگردد که چون در فرهنگ واژگان این کلمه مفهومی ندارد بنابراین همان ایشان بر می گردد که نمی دانم آیا راهکار صحیحی است یا خیر؟
2- استمر در برخورد با واژه "اجرای" واژه "اجر" را بر می گرداند که در حقیقت "ی" و "ا" را حذف کرده و چون واژه "اجر" در لیست کلمات وجود دارد آن را بر می گرداند. آیا راه حلی برای این موضوع هست؟
3- استمر نمی تواند واژه هایی مانند "زیبایی های" را به زیبا تبدیل کند (به دلیل ترتیبی که در حذف پسوندها وجود دارد فقط "ی" و "ها" حذف می شوند و چون "یی" قبل از حروف فوق چک شده بود دیگر چک نمی گردد و چون در دایره لغات "زیبایی" وجود ندارد بنابراین اصل واژه یعنی "زیبایی های" بر می گردد). آیا راه حلی برای این مشکل وجود دارد؟
4- استمر حرف "ا" را از انتهای قیدهایی مانند "اصلا" حذف می کند و آن ها را تبدیل به واژه "اصل" می کند.
5-استمر توانایی تبدیل واژه هایی مانند "پرندگان" را به "پرنده" ندارد که البته با قدری اصلاح کد قابل حل است.
6- آیا می توانم بپرسم که چرا از ماشین حالت متناهی آقای[ تقوی ](http://dl.acm.org/citation.cfm?id=1059059)یا [خانم رشیدی](https://arxiv.org/abs/1403.2837) در استمر برای حذف پسوندهای جمع و مالکیت و تفضیلی استفاده نکرده اید؟ به نظر بنده در صورتی که از یک ماشین حالت متناهی در تشخیص پسوندها استفاده شود تمامی مشکلات بالا حل خواهد شد.
البته نکته قابل ذکر این است که من از نسخه سی شارپ استفاده می کنم اما زمانی که کد پایتون و سی شارپ را مقایسه کردم، مکانیزم واحدی را در استمر مشاهده کردم.</div>

**Comment by janamhosein** [comment]
در طول مدت زمانی که هنوز از شما پاسخی دریافت نکردم تلاش کردم که استمر را توسط یک ماشین حالت متناهی که شبیه به ماشین حالت متناهی ذکر شده در مقالات ذکرشده، است را پیاده سازی کنم. جالب است که بدانید استمر حاصل را با استمر شما مقایسه کردم و نتایج بهتری دریافت گردید (ضعف های بالا پوشیده شد). اما هنوز هم برای من جای سوال است که چرا از این الگوریتم ها استفاده نشده، آیا مشکل خاصی بوجود می آورند؟ اگر اینطور نیست ، بنده کد استمری که نوشتم را در همینجا، در دسترس عموم قرار دهم.

**Comment by ahangarha** [comment]
لطف کنید این کد رو اول متن بگذارید که راست به چپ شود

    <div dir="rtl">

**Comment by nournia** [comment]
<div dir=rtl>

سلام
خیلی ممنون از پیشنهاد خوب شما. همونطور که خودتون گفتید، استمر هضم حالت ساده‌ای داره و بیشتر سرعت رو مورد توجه قرار داده.

خیلی خوب می‌شه که شما بتونید به ارتقای استمر هضم کمک کنید.

**Comment by janamhosein** [comment]
<div dir="rtl">با سلام. درتلاش برای بهبود نهایی الگوریتم هستم. سعی می کنم که در اولین فرصت الگوریتم را منتشر کنم.</div>
